export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const TOP_FIVE_PRODUCT_LIST_REQUEST = 'TOP_FIVE_PRODUCT_LIST_REQUEST'
export const TOP_FIVE_PRODUCT_LIST_SUCCESS = 'TOP_FIVE_PRODUCT_LIST_SUCCESS'
export const TOP_FIVE_PRODUCT_LIST_FAIL = 'TOP_FIVE_PRODUCT_LIST_FAIL'

export const TODAY_SALE_REQUEST = 'TODAY_SALE_REQUEST'
export const TODAY_SALE_SUCCESS = 'TODAY_SALE_SUCCESS'
export const TODAY_SALE_FAIL = 'TODAY_SALE_FAIL'